version: "3"

silent: true

tasks:
  default:
    desc: Run the binary in "dev mode"
    summary: |
      Run the binary for development needs.

      This command will build a development version of the tool before invoking it in
      the current shell environment. Do note, this will run an unoptimised version of
      the tool and is only useful during development.
    cmd: go run main.go

  build:
    desc: Build the binary for the current system architecture.
    summary: |
      Compile and build the binary.

      This command will compile the source code and build the binary for the current
      system architecture. Do note, it will not build the binary for the target
      architecture unless specified.
    cmd: go build -o ./bin/forge
    sources:
      - "*.go"
    generates:
      - ./bin/forge*

  docs:
    desc: Run the dev server for the docs.
    summary: |
      Run the dev server for the docs.

      This command will intelligently run the documentation's server from the
      appropriate directory. Use this command during development to work on the docs or
      use it for local reference.
    dir: ./docs
    cmd: pnpm dev
    sources:
      - package.json
    generates:
      - pnpm-lock.json
