name: Create a Pre-Release

on:
  push:
    tags:
      - v**.**.**-alpha

permissions:
  contents: write

jobs:
  create-release:
    name: Create a Pre-Release Version
    runs-on: ubuntu-latest
    steps:
      - name: Create Pre-Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="v${TAG#v}" \
            --generate-notes \
            --prerelease
